name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  common:
    name: Pre-commit and Test CI
    runs-on: ubuntu-latest

    needs: [pre-commit, test]
    uses: ./.github/workflows/common.yaml
    
  bump-version:
    name: Bump Version
    needs: common
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: |
          pdm install -G :all
      - name: Install bump
        run: |
          pdm self add pdm-bump
      - name: Bump Version
        run: |
          pdm bump auto
      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git push origin main --tags

  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
      - name: Install dependencies
        run: |
          pdm install -G :all
      - name: Build
        run: |
          pdm build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/*.whl
    